# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_URL=redis://redis:6379/0
    secrets:
      - source: database_url
        mode: 444
      - source: admin_username
        mode: 444
      - source: admin_password
        mode: 444
      - source: partner_id
        mode: 444
      - source: partner_key
        mode: 444
      - source: shop_id
        mode: 444
      - source: shopee_url
        mode: 444
      - source: access_token
        mode: 444
      - source: refresh_token
        mode: 444

  db:
    image: postgres:18.4-alpine
    restart: always
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=bakingholic
      - APP_PASSWORD=/run/secrets/app_password
    volumes:
      - db-data:/var/lib/postgresql
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    secrets:
      - postgres_password
      - app_password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bakingholic" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.8-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  db-data:
  redis-data:

secrets:
  database_url:
    environment: DATABASE_URL
  admin_username:
    environment: ADMIN_USERNAME
  admin_password:
    environment: ADMIN_PASSWORD
  partner_id:
    environment: PARTNER_ID
  partner_key:
    environment: PARTNER_KEY
  shop_id:
    environment: SHOP_ID
  shopee_url:
    environment: SHOPEE_URL
  access_token:
    environment: ACCESS_TOKEN
  refresh_token:
    environment: REFRESH_TOKEN
  postgres_password:
    file: ./.secrets/postgres_password
  app_password:
    file: ./.secrets/app_password
