"""refactor outbound tags

Revision ID: 9383471fa90d
Revises: aa5a426a95ff
Create Date: 2026-06-11 15:27:58.151969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9383471fa90d'
down_revision: Union[str, Sequence[str], None] = 'aa5a426a95ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outbound_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['outbound_id'], ['orders.outbound_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_tags_content'), 'tags', ['content'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_tags_id'), 'tags', ['id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_tags_outbound_id'), 'tags', ['outbound_id'], unique=False, schema='orders')
    op.drop_column('outbound_items', 'tag', schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_items', sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=True), schema='orders')
    op.drop_index(op.f('ix_orders_tags_outbound_id'), table_name='tags', schema='orders')
    op.drop_index(op.f('ix_orders_tags_id'), table_name='tags', schema='orders')
    op.drop_index(op.f('ix_orders_tags_content'), table_name='tags', schema='orders')
    op.drop_table('tags', schema='orders')
    # ### end Alembic commands ###
