"""initial schema

Revision ID: e09271f5005e
Revises: 
Create Date: 2026-06-03 15:54:53.438565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e09271f5005e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_username'), 'users', ['username'], unique=False, schema='auth')
    op.create_table('pick_item_entries_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_pick_item_entries_log_id'), 'pick_item_entries_log', ['id'], unique=False, schema='orders')
    op.create_table('items',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sku'),
    schema='warehouse'
    )
    op.create_index(op.f('ix_warehouse_items_item_name'), 'items', ['item_name'], unique=False, schema='warehouse')
    op.create_index(op.f('ix_warehouse_items_sku'), 'items', ['sku'], unique=False, schema='warehouse')
    op.create_table('stocks_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='warehouse'
    )
    op.create_index(op.f('ix_warehouse_stocks_log_id'), 'stocks_log', ['id'], unique=False, schema='warehouse')
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['auth.users.username'], ),
    sa.PrimaryKeyConstraint('jti'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False, schema='auth')
    op.create_table('outbound_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_user', sa.String(), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user'], ['auth.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_outbound_items_id'), 'outbound_items', ['id'], unique=False, schema='orders')
    op.create_table('orders',
    sa.Column('order_sn', sa.String(), nullable=False),
    sa.Column('split_up', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('owner_user', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user'], ['auth.users.username'], ),
    sa.PrimaryKeyConstraint('order_sn'),
    schema='shopee'
    )
    op.create_index(op.f('ix_shopee_orders_order_sn'), 'orders', ['order_sn'], unique=False, schema='shopee')
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['warehouse.items.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='warehouse'
    )
    op.create_index(op.f('ix_warehouse_stocks_id'), 'stocks', ['id'], unique=False, schema='warehouse')
    op.create_table('pick_item_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('order_sn', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('owner_user', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['order_sn'], ['shopee.orders.order_sn'], ),
    sa.ForeignKeyConstraint(['owner_user'], ['auth.users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_pick_item_entries_id'), 'pick_item_entries', ['id'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_pick_item_entries_sku'), 'pick_item_entries', ['sku'], unique=False, schema='orders')
    op.create_table('order_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_sn', sa.String(), nullable=False),
    sa.Column('package_number', sa.String(), nullable=True),
    sa.Column('logistics_status', sa.String(), nullable=True),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('pickup_code', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_sn'], ['shopee.orders.order_sn'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shopee'
    )
    op.create_index(op.f('ix_shopee_order_info_id'), 'order_info', ['id'], unique=False, schema='shopee')
    op.create_table('order_item_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_sn', sa.String(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_sku', sa.String(), nullable=True),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('model_sku', sa.String(), nullable=True),
    sa.Column('model_quantity_purchased', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_sn'], ['shopee.orders.order_sn'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shopee'
    )
    op.create_index(op.f('ix_shopee_order_item_list_id'), 'order_item_list', ['id'], unique=False, schema='shopee')
    op.create_table('order_recipient_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_sn', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_sn'], ['shopee.orders.order_sn'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='shopee'
    )
    op.create_index(op.f('ix_shopee_order_recipient_address_id'), 'order_recipient_address', ['id'], unique=False, schema='shopee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopee_order_recipient_address_id'), table_name='order_recipient_address', schema='shopee')
    op.drop_table('order_recipient_address', schema='shopee')
    op.drop_index(op.f('ix_shopee_order_item_list_id'), table_name='order_item_list', schema='shopee')
    op.drop_table('order_item_list', schema='shopee')
    op.drop_index(op.f('ix_shopee_order_info_id'), table_name='order_info', schema='shopee')
    op.drop_table('order_info', schema='shopee')
    op.drop_index(op.f('ix_orders_pick_item_entries_sku'), table_name='pick_item_entries', schema='orders')
    op.drop_index(op.f('ix_orders_pick_item_entries_id'), table_name='pick_item_entries', schema='orders')
    op.drop_table('pick_item_entries', schema='orders')
    op.drop_index(op.f('ix_warehouse_stocks_id'), table_name='stocks', schema='warehouse')
    op.drop_table('stocks', schema='warehouse')
    op.drop_index(op.f('ix_shopee_orders_order_sn'), table_name='orders', schema='shopee')
    op.drop_table('orders', schema='shopee')
    op.drop_index(op.f('ix_orders_outbound_items_id'), table_name='outbound_items', schema='orders')
    op.drop_table('outbound_items', schema='orders')
    op.drop_index(op.f('ix_auth_refresh_tokens_jti'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_auth_refresh_tokens_expires_at'), table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    op.drop_index(op.f('ix_warehouse_stocks_log_id'), table_name='stocks_log', schema='warehouse')
    op.drop_table('stocks_log', schema='warehouse')
    op.drop_index(op.f('ix_warehouse_items_sku'), table_name='items', schema='warehouse')
    op.drop_index(op.f('ix_warehouse_items_item_name'), table_name='items', schema='warehouse')
    op.drop_table('items', schema='warehouse')
    op.drop_index(op.f('ix_orders_pick_item_entries_log_id'), table_name='pick_item_entries_log', schema='orders')
    op.drop_table('pick_item_entries_log', schema='orders')
    op.drop_index(op.f('ix_auth_users_username'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
