"""add shopee.orders.shipping_carrier

Revision ID: aa5a426a95ff
Revises: e2d7906a02ff
Create Date: 2026-06-11 15:26:48.757206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa5a426a95ff"
down_revision: Union[str, Sequence[str], None] = "e2d7906a02ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders",
        sa.Column("shipping_carrier", sa.String(), nullable=True),
        schema="shopee",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "shipping_carrier", schema="shopee")
    # ### end Alembic commands ###
