"""empty message

Revision ID: d862d86e8707
Revises: 4e6ef916e20d
Create Date: 2026-07-19 19:34:42.307072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d862d86e8707"
down_revision: Union[str, Sequence[str], None] = "4e6ef916e20d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bom_details",
        "quantity_standard",
        existing_type=sa.INTEGER(),
        nullable=False,
        schema="warehouse",
    )
    op.alter_column("items", "barcode_supplier", new_column_name="supplier_barcode")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("items", "supplier_barcode", new_column_name="barcode_supplier")
    op.alter_column(
        "bom_details",
        "quantity_standard",
        existing_type=sa.INTEGER(),
        nullable=True,
        schema="warehouse",
    )
    # ### end Alembic commands ###
