"""rename created_at to ship_by

Revision ID: bcc1283662c5
Revises: e09271f5005e
Create Date: 2026-06-03 19:35:56.569683

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcc1283662c5"
down_revision: Union[str, Sequence[str], None] = "e09271f5005e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "created_at", new_column_name="ship_by", schema="shopee")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("orders", "ship_by", new_column_name="created_at", schema="shopee")
    # ### end Alembic commands ###
