"""add index for outbound logic

Revision ID: e2d7906a02ff
Revises: bcc1283662c5
Create Date: 2026-06-06 12:13:37.600456

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e2d7906a02ff'
down_revision: Union[str, Sequence[str], None] = 'bcc1283662c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_outbound_items_content'), 'outbound_items', ['content'], unique=False, schema='orders')
    op.create_index(op.f('ix_shopee_order_info_tracking_number'), 'order_info', ['tracking_number'], unique=False, schema='shopee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopee_order_info_tracking_number'), table_name='order_info', schema='shopee')
    op.drop_index(op.f('ix_orders_outbound_items_content'), table_name='outbound_items', schema='orders')
    # ### end Alembic commands ###
