"""add bom

Revision ID: 4e6ef916e20d
Revises: 9383471fa90d
Create Date: 2026-06-15 15:52:14.797613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6ef916e20d'
down_revision: Union[str, Sequence[str], None] = '9383471fa90d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom_headers_marketplace',
    sa.Column('shopee_id', sa.BigInteger(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('quantity_standard', sa.Integer(), nullable=True),
    sa.Column('marketplace', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('shopee_id'),
    schema='warehouse'
    )
    op.create_table('bom_details_marketplace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shopee_id', sa.BigInteger(), nullable=False),
    sa.Column('component_sku', sa.String(), nullable=False),
    sa.Column('quantity_standard', sa.Integer(), nullable=True),
    sa.Column('is_not_primary_child', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_sku'], ['warehouse.items.sku'], ),
    sa.ForeignKeyConstraint(['shopee_id'], ['warehouse.bom_headers_marketplace.shopee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='warehouse'
    )
    op.create_table('bom_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('quantity_standard', sa.Integer(), nullable=True),
    sa.Column('factor_f5', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['warehouse.items.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    schema='warehouse'
    )
    op.create_table('shopee_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('has_variant', sa.Boolean(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('sell_price_factor', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('factor_x', sa.Float(), nullable=True),
    sa.Column('factor_plus', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sku'], ['warehouse.items.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='warehouse'
    )
    op.create_table('bom_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bom_header_id', sa.Integer(), nullable=False),
    sa.Column('component_sku', sa.String(), nullable=False),
    sa.Column('quantity_standard', sa.Integer(), nullable=True),
    sa.Column('is_not_primary_child', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bom_header_id'], ['warehouse.bom_headers.id'], ),
    sa.ForeignKeyConstraint(['component_sku'], ['warehouse.items.sku'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='warehouse'
    )
    op.add_column('items', sa.Column('uom', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('manufacturer', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('item_name_manufacturer', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('dimension_notes', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('sell_price', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('manufacturer_price', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('price_before_discount_tax', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('jar_length', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('jar_width', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('jar_height', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('box_length', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('box_width', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('box_height', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('qty_per_box', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('qty_per_pack', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('boxes_per_bundle', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('whole_uom', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('whole_deno', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('jar_group', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('moq', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('price_list_name', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('item_group', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('sell_price_bh', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('weight_per_pcs', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('hide_in_price_list', sa.Boolean(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('sku_factory', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('is_parent', sa.Boolean(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('is_child', sa.Boolean(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('sell_price_tokped', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('jar_type', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('jar_capacity_gr', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('top_length', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('top_width', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('bottom_length', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('bottom_width', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('height', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('sales_commission_percent', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('salesman_base_kelp_order', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('salesman_base_uom_order', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('salesman_base_price_list_intv', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('salesman_whole_uom_order', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('salesman_group_barang', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('exclude_stock_control', sa.Boolean(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('note', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('update_date', sa.DateTime(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('created_date', sa.DateTime(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('volume_m3', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('picture', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('lid_type', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('category', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('desc_label', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('barcode_supplier', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('item_value_intv', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('item_value_target', sa.Float(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('photo', sa.String(), nullable=True), schema='warehouse')
    op.add_column('items', sa.Column('weight_kg', sa.Float(), nullable=True), schema='warehouse')
    op.drop_column('items', 'location', schema='warehouse')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True), schema='warehouse')
    op.drop_column('items', 'weight_kg', schema='warehouse')
    op.drop_column('items', 'photo', schema='warehouse')
    op.drop_column('items', 'item_value_target', schema='warehouse')
    op.drop_column('items', 'item_value_intv', schema='warehouse')
    op.drop_column('items', 'barcode_supplier', schema='warehouse')
    op.drop_column('items', 'desc_label', schema='warehouse')
    op.drop_column('items', 'category', schema='warehouse')
    op.drop_column('items', 'lid_type', schema='warehouse')
    op.drop_column('items', 'picture', schema='warehouse')
    op.drop_column('items', 'volume_m3', schema='warehouse')
    op.drop_column('items', 'created_date', schema='warehouse')
    op.drop_column('items', 'update_date', schema='warehouse')
    op.drop_column('items', 'note', schema='warehouse')
    op.drop_column('items', 'exclude_stock_control', schema='warehouse')
    op.drop_column('items', 'salesman_group_barang', schema='warehouse')
    op.drop_column('items', 'salesman_whole_uom_order', schema='warehouse')
    op.drop_column('items', 'salesman_base_price_list_intv', schema='warehouse')
    op.drop_column('items', 'salesman_base_uom_order', schema='warehouse')
    op.drop_column('items', 'salesman_base_kelp_order', schema='warehouse')
    op.drop_column('items', 'sales_commission_percent', schema='warehouse')
    op.drop_column('items', 'height', schema='warehouse')
    op.drop_column('items', 'bottom_width', schema='warehouse')
    op.drop_column('items', 'bottom_length', schema='warehouse')
    op.drop_column('items', 'top_width', schema='warehouse')
    op.drop_column('items', 'top_length', schema='warehouse')
    op.drop_column('items', 'jar_capacity_gr', schema='warehouse')
    op.drop_column('items', 'jar_type', schema='warehouse')
    op.drop_column('items', 'sell_price_tokped', schema='warehouse')
    op.drop_column('items', 'is_child', schema='warehouse')
    op.drop_column('items', 'is_parent', schema='warehouse')
    op.drop_column('items', 'sku_factory', schema='warehouse')
    op.drop_column('items', 'hide_in_price_list', schema='warehouse')
    op.drop_column('items', 'weight_per_pcs', schema='warehouse')
    op.drop_column('items', 'sell_price_bh', schema='warehouse')
    op.drop_column('items', 'item_group', schema='warehouse')
    op.drop_column('items', 'price_list_name', schema='warehouse')
    op.drop_column('items', 'moq', schema='warehouse')
    op.drop_column('items', 'jar_group', schema='warehouse')
    op.drop_column('items', 'whole_deno', schema='warehouse')
    op.drop_column('items', 'whole_uom', schema='warehouse')
    op.drop_column('items', 'boxes_per_bundle', schema='warehouse')
    op.drop_column('items', 'qty_per_pack', schema='warehouse')
    op.drop_column('items', 'qty_per_box', schema='warehouse')
    op.drop_column('items', 'box_height', schema='warehouse')
    op.drop_column('items', 'box_width', schema='warehouse')
    op.drop_column('items', 'box_length', schema='warehouse')
    op.drop_column('items', 'jar_height', schema='warehouse')
    op.drop_column('items', 'jar_width', schema='warehouse')
    op.drop_column('items', 'jar_length', schema='warehouse')
    op.drop_column('items', 'price_before_discount_tax', schema='warehouse')
    op.drop_column('items', 'manufacturer_price', schema='warehouse')
    op.drop_column('items', 'sell_price', schema='warehouse')
    op.drop_column('items', 'dimension_notes', schema='warehouse')
    op.drop_column('items', 'item_name_manufacturer', schema='warehouse')
    op.drop_column('items', 'manufacturer', schema='warehouse')
    op.drop_column('items', 'uom', schema='warehouse')
    op.drop_table('bom_details', schema='warehouse')
    op.drop_table('shopee_items', schema='warehouse')
    op.drop_table('bom_headers', schema='warehouse')
    op.drop_table('bom_details_marketplace', schema='warehouse')
    op.drop_table('bom_headers_marketplace', schema='warehouse')
    # ### end Alembic commands ###
